Standard task runes
datatrails/go-datatrails-common pull request #86
Opened 2024-08-20 08:37 UTC by eccles

Also ensure that go.mod is up to date

AB#9472

2024-08-20 09:03 UTC, j-hartley requested changes

2024-08-20 09:17 UTC, eccles commented on taskfiles/Taskfile_codeqa.yml
> +      - |
fixed

2024-08-20 09:17 UTC, eccles commented on taskfiles/Taskfile_codeqa.yml
> +      - |
fixed

2024-08-20 10:00 UTC, robinbryce requested changes
I don't think we want to resolve the version of grpc-gatway this way

2024-08-20 10:01 UTC, robinbryce commented on taskfiles/Taskfile_codeqa.yml
> +        GATEWAYVERSION=$(protoc-gen-grpc-gateway -version | cut -d',' -f1 | cut -d' ' -f2)
If this is controversial, I suggest you move this change to a different PR so it can be addressed in isolation

2024-08-21 09:16 UTC, robinbryce approved these changes
LGTM

2024-08-21 09:52 UTC, merged